# Generated by Django 3.2.13 on 2022-12-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_photo_image'),
        ('community', '0003_auto_20221207_1333'),
    ]

    operations = [
    ]
