# Generated by Django 3.2.13 on 2022-12-05 00:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='art',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('전시', '전시'), ('영화', '영화'), ('뮤지컬', '뮤지컬'), ('공연', '공연'), ('디자인', '디자인'), ('박물관', '박물관'), ('연극', '연극'), ('콘서트', '콘서트'), ('연주회', '연주회'), ('페스티벌', '페스티벌')], max_length=4),
        ),
    ]
