# Generated by Django 3.2.13 on 2022-12-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='received_mail',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
