# Generated by Django 3.2.13 on 2022-12-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follwings',
            new_name='followings',
        ),
    ]
