# Generated by Django 3.2.13 on 2022-11-28 12:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='develop',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('습관만들기', '습관만들기'), ('챌린지', '챌린지'), ('독서', '독서'), ('스터디', '스터디'), ('외국어', '외국어'), ('재테크', '재테크'), ('브랜딩', '브랜딩'), ('커리어', '커리어'), ('사이드프로젝트', '사이드프로젝트')], default=4, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='food',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('맛집투어', '맛집투어'), ('카페', '카페'), ('와인', '와인'), ('커피', '커피'), ('디저트', '디저트'), ('맥주', '맥주'), ('티룸', '티룸'), ('비건', '비건'), ('파인다이닝', '파인다이닝'), ('요리', '요리'), ('페어링', '페어링'), ('칵테일', '칵테일'), ('위스키', '위스키'), ('전통주', '전통주')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
