# Generated by Django 3.2.13 on 2022-12-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_follwings_user_followings'),
        ('accounts', '0002_user_image'),
    ]

    operations = [
    ]
