# Generated by Django 3.2.13 on 2022-12-02 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='like_user',
            field=models.ManyToManyField(related_name='like_hobby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HobbyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.hobby')),
                ('like_user', models.ManyToManyField(related_name='like_comment', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
