# Generated by Django 3.2.13 on 2022-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='entry_fee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
