# Generated by Django 3.2.13 on 2022-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='X',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='Y',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hits',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
