# Generated by Django 3.2.13 on 2022-12-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_alter_hobby_entry_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
