# Generated by Django 3.2.13 on 2022-12-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0003_alter_hobby_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
